services:
  - type: web
    name: restaurant-order-tracker-api
    runtime: node
    rootDir: Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
